name: Actionlint

on:
  pull_request:
    branches: [main]

jobs:
  actionlint:
    name: GitHub Actions Workflow Validation
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run actionlint
        uses: reviewdog/action-actionlint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          filter_mode: added
          fail_level: error
